/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VOID = 5;
  /** RegularExpression Id. */
  int MAIN = 6;
  /** RegularExpression Id. */
  int LET = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int BOOL = 10;
  /** RegularExpression Id. */
  int TRUE = 11;
  /** RegularExpression Id. */
  int FALSE = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int PRINTIO = 14;
  /** RegularExpression Id. */
  int READIO = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int DEF = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int MULT = 22;
  /** RegularExpression Id. */
  int DIV = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int GT = 27;
  /** RegularExpression Id. */
  int EQ = 28;
  /** RegularExpression Id. */
  int ACHAVES = 29;
  /** RegularExpression Id. */
  int FCHAVES = 30;
  /** RegularExpression Id. */
  int APAREN = 31;
  /** RegularExpression Id. */
  int FPAREN = 32;
  /** RegularExpression Id. */
  int VIRGULA = 33;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 34;
  /** RegularExpression Id. */
  int ATRIBUICAO = 35;
  /** RegularExpression Id. */
  int NUM = 36;
  /** RegularExpression Id. */
  int ID = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"void\"",
    "\"main\"",
    "\"let\"",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"return\"",
    "\"printIO\"",
    "\"readIO\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"def\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\":=\"",
    "<NUM>",
    "<ID>",
  };

}
