/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VOID = 5;
  /** RegularExpression Id. */
  int MAIN = 6;
  /** RegularExpression Id. */
  int LET = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int PRINTIO = 9;
  /** RegularExpression Id. */
  int ACHAVES = 10;
  /** RegularExpression Id. */
  int FCHAVES = 11;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 12;
  /** RegularExpression Id. */
  int ATRIBUICAO = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int ID = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"void\"",
    "\"main\"",
    "\"let\"",
    "\"float\"",
    "\"printIO\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":=\"",
    "<NUM>",
    "<ID>",
  };

}
